config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show]
  
  resources :groups, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    member do
      get :invitation_link
      get 'join/:token', to: 'groups#join', as: 'join_with_token'
      post 'join', to: 'groups#join_group', as: 'join_group'
    end

    resources :blogs do
      resources :likes, only: [:create]
      resources :comments, only: [:create]
      collection do
        get "season/:season", to: "blogs#season", as: :season
      end
    end
    resources :tweets, only: [:show, :new, :create, :edit, :update, :destroy] do
      resources :likes, only: [:create]
      resources :comments, only: [:create]
    end
  end

  root 'hello#index'
  get 'hello/index' => 'hello#index'
  get 'hello/link' => 'hello#link'
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  belongs_to :group   # どのグループの投稿かを紐付け
  has_many_attached :images
  has_many :likes, as: :likeable
  has_many :liked_users, through: :likes, source: :user
  has_many :comments, as: :commentable, dependent: :destroy
  has_many_attached :images

  validate :images_presence   # ← ここで呼ぶ

  private

  def images_presence
    errors.add(:images, "を1枚以上アップロードしてください") unless images.attached?
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group


  def new
    @tweet = @group.tweets.new
  end

def create
  @tweet = @group.tweets.new(tweet_params)
  @tweet.user = current_user

  if @tweet.save
    redirect_to group_path(@group)  # ← 1回だけ
  else
    render :new, status: :unprocessable_entity
  end
end

  def show
    @tweet = Tweet.find(params[:id])
    @comments = @tweet.comments
    @comment = Comment.new
    @members = @group.users
    @group_lists = Group.all
    @group_joining = GroupUser.where(user_id: current_user.id)
    @group_lists_none = "グループに参加していません。"
  end

  def edit
    @tweet = Tweet.find(params[:id])
    @members = @group.users
    @group_lists = Group.all
    @group_joining = GroupUser.where(user_id: current_user.id)
    @group_lists_none = "グループに参加していません。"
  end

  def update
    tweet = Tweet.find(params[:id])
    if tweet.update(tweet_params)
      redirect_to :action => "show", :id => tweet.id
    else
      redirect_to :action => "new"
    end
  end

  def destroy
    @group = Group.find(params[:group_id])
    @tweet = @group.tweets.find(params[:id])

    @tweet.destroy
    redirect_to group_path(@group), notice: "削除しました"
  end

  private
  def tweet_params
    params.require(:tweet).permit(:body, images: [])
  end

  def set_group
    @group = Group.find(params[:group_id])
    session[:last_group_id] = @group.id
  end


end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/edit.html.erb
<div class="edit-tweet">
  <h3>投稿を編集</h3>

  <%= form_for [@group, @tweet], html: { id: "edit-form" } do |f| %>
    <div class="field">
      <%= f.label :キャプション %>
      <%= f.text_field :body, size: 140 %>
    </div>

    <%= f.submit "変更を保存" %>
  <% end %>

  <%= link_to "一覧に戻る", group_path(@group) %>
</div>

app/views/tweets/index.html.erb
<h1>Hidamari+</h1>
<%= button_to 'ログアウト', destroy_user_session_path, method: :delete %>
<h3>投稿一覧</h3>
<%= link_to "新規投稿へ", new_tweet_path %>
<div class="tweets-container">
    <% if user_signed_in? %>
        <%= link_to "マイページへ", user_path(current_user.id) %>
    <% end %>
    <% @tweets.each do |t| %>
        <div class="tweet">
            <% if t.user.image.attached? %>
                <%= image_tag  t.user.image, size: '250x200'%>
            <% end %>
            <% if t.image.attached? %>
                <%= image_tag t.image, size: '250x200'%>
            <% end %>
            <%= t.user.email %>
            <%= t.body %>
        <% if user_signed_in? %>
            <% if current_user.already_liked?(t) %>
                <%= link_to tweet_like_path(id: t.id, tweet_id: t.id), method: :delete do %>
                    <i class="fa-solid fa-heart" style="color:red;"></i>
                <% end %>
            <% else %>
                <%= link_to tweet_likes_path(id: t.id, tweet_id: t.id), method: :post do %>
                    <i class="fa-regular fa-heart"></i>
                <% end %>
            <% end %>
        <% else %>
            <i class="fa-regular fa-heart"></i>
        <% end %>
            <%= t.created_at %>
            <%= link_to "詳細へ", tweet_path(t.id) %>
            <%= link_to "編集する", edit_tweet_path(t.id) %>
            <%= button_to "削除する", tweet_path(t.id), method: :delete %>
        </div>
    <% end %>
</div>

app/views/tweets/new.html.erb
<div class="new-tweet">
  <h3>新規投稿</h3>

<%= form_with(model: [@group, @tweet],
              local: true,
              data: { turbo: false },
              html: { id: 'upload-form' }) do |f| %>

    <!-- ★ エラーメッセージを表示する場所（ここに追加！） -->
  <% if @tweet.errors.any? %>
    <div class="error-messages">
      <ul>
        <% @tweet.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <!-- ★ ここまで -->


  <div class="field">
    <%= f.label :キャプション %>
    <%= f.text_field :body, size: 140 %>
  </div>

  <!-- ★ 画像アップロード（複数対応） -->
  <div class="field">
    <%= f.file_field :images, multiple: true, 
          id: 'file-upload-input', style: 'display: none;' %>

    <%= f.label :images, "写真を追加",
          class: "add-photo-button",
          for: 'file-upload-input' %>
    <!-- ★ 追加 -->
  <p id="selected-files" class="file-status"></p>
</div>

  <%= f.submit "投稿する", data: { turbo: false } %>
<% end %>

<%= link_to "一覧に戻る", group_path(@group) %>

<script>
  document.addEventListener("turbo:load", () => {
    const input = document.getElementById("file-upload-input");
    const status = document.getElementById("selected-files");
    const form = document.getElementById("upload-form");

    if (!input || !status || !form) return;

    input.addEventListener("change", (e) => {
      // ★ 勝手に submit されるのを防ぐ
      e.preventDefault();
      e.stopPropagation();

      if (input.files.length === 0) {
        status.textContent = "";
      } else if (input.files.length === 1) {
        status.textContent = "写真を1枚選択しました";
      } else {
        status.textContent = `写真を${input.files.length}枚選択しました`;
      }
    });

    // 念のため submit を監視（デバッグ用）
    form.addEventListener("submit", () => {
      console.log("🚨 submit fired");
    });
  });
</script>
</div>

app/views/tweets/show.html.erb

<div class="tweet-show">


<div class="tweet-show-images">
  <% if @tweet.images.attached? %>
    <% @tweet.images.each do |img| %>
      <%= image_tag img, class: "show-image" %>
    <% end %>
  <% end %>
</div>


<% if user_signed_in? %>
  <%= button_to group_tweet_likes_path(@group, @tweet), method: :post do %>
    <i class="fas fa-heart" style="color: red;"></i> <%= @tweet.likes.count %>
  <% end %>
<% else %>
  <i class="fas fa-heart" style="color: red;"></i> <%= @tweet.likes.count %>
<% end %>

  <p><%= @tweet.created_at.strftime("%Y-%m-%d") %></p>
  <div class="tweet-actions">
  <%= link_to "編集する", edit_group_tweet_path(@group, @tweet), class: "action-button"%>
  <%= button_to "削除する", group_tweet_path(@group, @tweet),
      method: :delete,
      class: "action-button",
      data: { confirm: "本当に削除しますか？" } %>
  </div>
  

</div>


<div class="comment-wrapper">

<% mine = (@tweet.user == current_user) %>
<div class="comment-bubble <%= mine ? "mine" : "theirs" %>">
  <div class="comment-icon">
    <% if @tweet.user.image.attached? %>
      <%= image_tag @tweet.user.image, size: '50x50' %>
    <% else %>
          <div class="icon-placeholder"></div>
    <% end %>
  </div>
  <div class="comment-body">
        <div class="comment-name"><%= @tweet.user.profile %></div>
        <div class="comment-text"><%= @tweet.body %></div>
      </div>
    </div>

  <% @comments.each do |c| %>
    <% mine = (c.user == current_user) %>

    <div class="comment-bubble <%= mine ? "mine" : "theirs" %>">
      <div class="comment-icon">
        <% if c.user.image.attached? %>
          <%= image_tag c.user.image, size: '40x40' %>
        <% else %>
          <div class="icon-placeholder"></div>
        <% end %>
      </div>

      <div class="comment-body">
        <div class="comment-name"><%= c.user.profile %></div>
        <div class="comment-text"><%= c.content %></div>
      </div>
    </div>
  <% end %>

  <% if user_signed_in? %>
    <% @comment ||= Comment.new %>

    <div class="comment-form">
      <%= form_with(model: [@group, @tweet, @comment], local: true) do |f| %>
        <%= f.text_area :content, class: "comment-input" %>
        <%= button_tag type: "submit", class: "action-button" do %>
          コメントする
        <% end %>
      <% end %>
    </div>
  <% end %>


<%= link_to "コレミテページに戻る", group_path(@group) %>
</div>


<script>
  document.addEventListener("DOMContentLoaded", function () {
    new Swiper(".mySwiper", {
      loop: false,
      pagination: {
        el: ".swiper-pagination",
        clickable: true,
      },
      navigation: {
        nextEl: ".swiper-button-next",
        prevEl: ".swiper-button-prev",
      },
    });
  });
</script>